In [1]:
import pandas as pd
import numpy as np
import copy

In [2]:
df = pd.read_excel('./run4_correctcarboncosts/AllCarbonNumbers_080922.xlsx')
num_rows = df.shape[0]
df.insert(0, 'Net_Carbon', [0] * num_rows)

START_YEAR = 2021
FOR_TYPES = list(set(df['StandID']))
YEARS = list(set(df['Year']))
MNGS = list(set(df['MgmtID']))

df.sort_values(['StandID', 'MgmtID', 'Year'])


Net_Carbon        Variable StandID MgmtID  Year  Total_Stand_Carbon  \
0            0    505_2021_ASV     505    ASV  2021           55.202126   
4            0    505_2025_ASV     505    ASV  2025           59.408627   
8            0    505_2030_ASV     505    ASV  2030           63.405056   
12           0    505_2050_ASV     505    ASV  2050           94.440681   
1            0    505_2021_IFM     505    IFM  2021           52.616356   
5            0    505_2025_IFM     505    IFM  2025           54.112751   
9            0    505_2030_IFM     505    IFM  2030           57.430019   
13           0    505_2050_IFM     505    IFM  2050           78.380608   
2            0   505_2021_PLSQ     505   PLSQ  2021           55.080078   
6            0   505_2025_PLSQ     505   PLSQ  2025           59.402340   
10           0   505_2030_PLSQ     505   PLSQ  2030           64.457832   
14           0   505_2050_PLSQ     505   PLSQ  2050           90.431480   
3            0   505_2021_THNB     505   THNB  2021           53.693821   
7            0   505_2025_THNB     505   THNB  2025           55.107147   
11           0   505_2030_THNB     505   THNB  2030           58.010864   
15           0   505_2050_THNB     505   THNB  2050           85.731613   
16           0    608_2021_AWR     608    AWR  2021           27.277493   
18           0    608_2025_AWR     608    AWR  2025           21.594889   
20           0    608_2030_AWR     608    AWR  2030           21.131365   
22           0    608_2050_AWR     608    AWR  2050           46.702976   
17           0   608_2021_PLSQ     608   PLSQ  2021           45.944687   
19           0   608_2025_PLSQ     608   PLSQ  2025           49.188103   
21           0   608_2030_PLSQ     608   PLSQ  2030           52.375256   
23           0   608_2050_PLSQ     608   PLSQ  2050           67.609947   
24           0    999_2021_AWR     999    AWR  2021            4.822156   
29           0    999_2025_AWR     999    AWR  2025            4.359046   
34           0    999_2030_AWR     999    AWR  2030            6.590279   
39           0    999_2050_AWR     999    AWR  2050           30.151794   
25           0    999_2021_CAR     999    CAR  2021            4.822156   
30           0    999_2025_CAR     999    CAR  2025            4.115263   
35           0    999_2030_CAR     999    CAR  2030            4.938148   
40           0    999_2050_CAR     999    CAR  2050           23.613348   
26           0    999_2021_NAR     999    NAR  2021            4.824862   
31           0    999_2025_NAR     999    NAR  2025            3.923987   
36           0    999_2030_NAR     999    NAR  2030            4.108756   
41           0    999_2050_NAR     999    NAR  2050           19.555927   
27           0   999_2021_PLSQ     999   PLSQ  2021            7.028458   
32           0   999_2025_PLSQ     999   PLSQ  2025            6.927432   
37           0   999_2030_PLSQ     999   PLSQ  2030            7.025498   
42           0   999_2050_PLSQ     999   PLSQ  2050            8.275467   
28           0    999_2021_SAR     999    SAR  2021            4.822156   
33           0    999_2025_SAR     999    SAR  2025            4.186758   
38           0    999_2030_SAR     999    SAR  2030            5.298999   
43           0    999_2050_SAR     999    SAR  2050           26.015049   
44           0  167N_2021_PLSQ    167N   PLSQ  2021           35.021587   
46           0  167N_2025_PLSQ    167N   PLSQ  2025           36.869949   
48           0  167N_2030_PLSQ    167N   PLSQ  2030           36.483826   
50           0  167N_2050_PLSQ    167N   PLSQ  2050           43.433018   
45           0  167N_2021_THNB    167N   THNB  2021           34.437302   
47           0  167N_2025_THNB    167N   THNB  2025           35.482277   
49           0  167N_2030_THNB    167N   THNB  2030           36.572166   
51           0  167N_2050_THNB    167N   THNB  2050           57.759636   
52           0  167S_2021_PLS

## What We Want To Do
 - 1) Turn stand carbon into net sequestration
 - 2) Add harvested product
 - 3) Subtract carbon costs

## 1 - Net Sequestration
We add a new column, net_carbon, which for each entry is equal to the net change in Total_Stand_Carbon from
one year to the next.

For 2021, we compare against the no management (PLSQ) for each forest type.

In [3]:
# Baseline extraction - we generate a dataframe which gives the Start Year PLSQ for each forest type
df_baseline = df[df['Year'] == START_YEAR]
df_baseline = df_baseline[df_baseline['MgmtID'] == 'PLSQ']

# We only care about these two columns
df_baseline = df_baseline[['Year', 'StandID', 'Total_Stand_Carbon']]
df_baseline = df_baseline.rename(columns={
    'Total_Stand_Carbon': 'Baseline_Carbon_2021'
})
df_baseline

Year StandID  Baseline_Carbon_2021
2   2021     505             55.080078
17  2021     608             45.944687
27  2021     999              7.028458
44  2021    167N             35.021587
52  2021    167S             37.369804

In [5]:
# Calculate Net Carbon
# Step 1: Take difference between year to year

# This is achieved by sorting correctly, and then subtracting consecutive rows
# See: https://datagy.io/pandas-shift/
df_seq = df.sort_values(['StandID', 'MgmtID'])
df_seq['Shifted Carbon'] = df_seq['Total_Stand_Carbon'].shift(periods=1, fill_value=0)
df_seq['Net_Carbon'] = df_seq['Total_Stand_Carbon'] - df_seq['Shifted Carbon']
df_seq

Net_Carbon        Variable StandID MgmtID  Year  Total_Stand_Carbon  \
0    55.202126    505_2021_ASV     505    ASV  2021           55.202126   
4     4.206501    505_2025_ASV     505    ASV  2025           59.408627   
8     3.996429    505_2030_ASV     505    ASV  2030           63.405056   
12   31.035625    505_2050_ASV     505    ASV  2050           94.440681   
1   -41.824326    505_2021_IFM     505    IFM  2021           52.616356   
5     1.496395    505_2025_IFM     505    IFM  2025           54.112751   
9     3.317268    505_2030_IFM     505    IFM  2030           57.430019   
13   20.950588    505_2050_IFM     505    IFM  2050           78.380608   
2   -23.300529   505_2021_PLSQ     505   PLSQ  2021           55.080078   
6     4.322262   505_2025_PLSQ     505   PLSQ  2025           59.402340   
10    5.055492   505_2030_PLSQ     505   PLSQ  2030           64.457832   
14   25.973648   505_2050_PLSQ     505   PLSQ  2050           90.431480   
3   -36.737659   505_2021_THNB     505   THNB  2021           53.693821   
7     1.413326   505_2025_THNB     505   THNB  2025           55.107147   
11    2.903717   505_2030_THNB     505   THNB  2030           58.010864   
15   27.720749   505_2050_THNB     505   THNB  2050           85.731613   
16  -58.454121    608_2021_AWR     608    AWR  2021           27.277493   
18   -5.682604    608_2025_AWR     608    AWR  2025           21.594889   
20   -0.463524    608_2030_AWR     608    AWR  2030           21.131365   
22   25.571611    608_2050_AWR     608    AWR  2050           46.702976   
17   -0.758289   608_2021_PLSQ     608   PLSQ  2021           45.944687   
19    3.243416   608_2025_PLSQ     608   PLSQ  2025           49.188103   
21    3.187153   608_2030_PLSQ     608   PLSQ  2030           52.375256   
23   15.234692   608_2050_PLSQ     608   PLSQ  2050           67.609947   
24  -62.787791    999_2021_AWR     999    AWR  2021            4.822156   
29   -0.463110    999_2025_AWR     999    AWR  2025            4.359046   
34    2.231233    999_2030_AWR     999    AWR  2030            6.590279   
39   23.561516    999_2050_AWR     999    AWR  2050           30.151794   
25  -25.329638    999_2021_CAR     999    CAR  2021            4.822156   
30   -0.706893    999_2025_CAR     999    CAR  2025            4.115263   
35    0.822885    999_2030_CAR     999    CAR  2030            4.938148   
40   18.675200    999_2050_CAR     999    CAR  2050           23.613348   
26  -18.788486    999_2021_NAR     999    NAR  2021            4.824862   
31   -0.900875    999_2025_NAR     999    NAR  2025            3.923987   
36    0.184769    999_2030_NAR     999    NAR  2030            4.108756   
41   15.447171    999_2050_NAR     999    NAR  2050           19.555927   
27  -12.527469   999_2021_PLSQ     999   PLSQ  2021            7.028458   
32   -0.101026   999_2025_PLSQ     999   PLSQ  2025            6.927432   
37    0.098066   999_2030_PLSQ     999   PLSQ  2030            7.025498   
42    1.249969   999_2050_PLSQ     999   PLSQ  2050            8.275467   
28   -3.453311    999_2021_SAR     999    SAR  2021            4.822156   
33   -0.635398    999_2025_SAR     999    SAR  2025            4.186758   
38    1.112241    999_2030_SAR     999    SAR  2030            5.298999   
43   20.716050    999_2050_SAR     999    SAR  2050           26.015049   
44    9.006538  167N_2021_PLSQ    167N   PLSQ  2021           35.021587   
46    1.848362  167N_2025_PLSQ    167N   PLSQ  2025           36.869949   
48   -0.386124  167N_2030_PLSQ    167N   PLSQ  2030           36.483826   
50    6.949192  167N_2050_PLSQ    167N   PLSQ  2050           43.433018   
45   -8.995716  167N_2021_THNB    167N   THNB  2021           34.437302   
47    1.044975  167N_2025_THNB    167N   THNB  2025           35.482277   
49    1.089890  167N_2030_THNB    167N   THNB  2030           36.572166   
51   21.187469  167N_2050_THNB    167N   THNB  2050           57.759636   
52  -20.389832  167S_2021_PLS

In [6]:
# Calculate Net Carbon
# Step 2: For 2021, subtract against PLSQ

# This adds a column with the 2021 PLSQ baseline numbers
df_seq = df_seq.merge(df_baseline, 
         how='left', 
         on=['Year', 'StandID'], 
         validate='many_to_one'
        )

df_seq['First_Year_Net_Carbon'] = df_seq['Total_Stand_Carbon'] - df_seq['Baseline_Carbon_2021']
df_seq['Net_Carbon'] = df_seq['First_Year_Net_Carbon'].fillna(df_seq['Net_Carbon'])
df_seq

Net_Carbon        Variable StandID MgmtID  Year  Total_Stand_Carbon  \
0     0.122047    505_2021_ASV     505    ASV  2021           55.202126   
1     4.206501    505_2025_ASV     505    ASV  2025           59.408627   
2     3.996429    505_2030_ASV     505    ASV  2030           63.405056   
3    31.035625    505_2050_ASV     505    ASV  2050           94.440681   
4    -2.463722    505_2021_IFM     505    IFM  2021           52.616356   
5     1.496395    505_2025_IFM     505    IFM  2025           54.112751   
6     3.317268    505_2030_IFM     505    IFM  2030           57.430019   
7    20.950588    505_2050_IFM     505    IFM  2050           78.380608   
8     0.000000   505_2021_PLSQ     505   PLSQ  2021           55.080078   
9     4.322262   505_2025_PLSQ     505   PLSQ  2025           59.402340   
10    5.055492   505_2030_PLSQ     505   PLSQ  2030           64.457832   
11   25.973648   505_2050_PLSQ     505   PLSQ  2050           90.431480   
12   -1.386257   505_2021_THNB     505   THNB  2021           53.693821   
13    1.413326   505_2025_THNB     505   THNB  2025           55.107147   
14    2.903717   505_2030_THNB     505   THNB  2030           58.010864   
15   27.720749   505_2050_THNB     505   THNB  2050           85.731613   
16  -18.667194    608_2021_AWR     608    AWR  2021           27.277493   
17   -5.682604    608_2025_AWR     608    AWR  2025           21.594889   
18   -0.463524    608_2030_AWR     608    AWR  2030           21.131365   
19   25.571611    608_2050_AWR     608    AWR  2050           46.702976   
20    0.000000   608_2021_PLSQ     608   PLSQ  2021           45.944687   
21    3.243416   608_2025_PLSQ     608   PLSQ  2025           49.188103   
22    3.187153   608_2030_PLSQ     608   PLSQ  2030           52.375256   
23   15.234692   608_2050_PLSQ     608   PLSQ  2050           67.609947   
24   -2.206302    999_2021_AWR     999    AWR  2021            4.822156   
25   -0.463110    999_2025_AWR     999    AWR  2025            4.359046   
26    2.231233    999_2030_AWR     999    AWR  2030            6.590279   
27   23.561516    999_2050_AWR     999    AWR  2050           30.151794   
28   -2.206302    999_2021_CAR     999    CAR  2021            4.822156   
29   -0.706893    999_2025_CAR     999    CAR  2025            4.115263   
30    0.822885    999_2030_CAR     999    CAR  2030            4.938148   
31   18.675200    999_2050_CAR     999    CAR  2050           23.613348   
32   -2.203596    999_2021_NAR     999    NAR  2021            4.824862   
33   -0.900875    999_2025_NAR     999    NAR  2025            3.923987   
34    0.184769    999_2030_NAR     999    NAR  2030            4.108756   
35   15.447171    999_2050_NAR     999    NAR  2050           19.555927   
36    0.000000   999_2021_PLSQ     999   PLSQ  2021            7.028458   
37   -0.101026   999_2025_PLSQ     999   PLSQ  2025            6.927432   
38    0.098066   999_2030_PLSQ     999   PLSQ  2030            7.025498   
39    1.249969   999_2050_PLSQ     999   PLSQ  2050            8.275467   
40   -2.206302    999_2021_SAR     999    SAR  2021            4.822156   
41   -0.635398    999_2025_SAR     999    SAR  2025            4.186758   
42    1.112241    999_2030_SAR     999    SAR  2030            5.298999   
43   20.716050    999_2050_SAR     999    SAR  2050           26.015049   
44    0.000000  167N_2021_PLSQ    167N   PLSQ  2021           35.021587   
45    1.848362  167N_2025_PLSQ    167N   PLSQ  2025           36.869949   
46   -0.386124  167N_2030_PLSQ    167N   PLSQ  2030           36.483826   
47    6.949192  167N_2050_PLSQ    167N   PLSQ  2050           43.433018   
48   -0.584286  167N_2021_THNB    167N   THNB  2021           34.437302   
49    1.044975  167N_2025_THNB    167N   THNB  2025           35.482277   
50    1.089890  167N_2030_THNB    167N   THNB  2030           36.572166   
51   21.187469  167N_2050_THNB    167N   THNB  2050           57.759636   
52    0.000000  167S_2021_PLS

In [7]:
# Cleanup - remove now unnecessary rows
df_seq = df_seq.drop(columns=[
    'Shifted Carbon', 
    'Baseline_Carbon_2021', 
    'First_Year_Net_Carbon',
    'Total_Stand_Carbon'
])

In [8]:
# df_mgcost.to_csv('./ObjectiveFile_MngCost_0802022.csv',
#               columns=['Variable', 'Net_Carbon'],
#               index=False
#              )

df_seq.to_csv('./run4_correctcarboncosts/Objective_NetSeq_NoHarvest_08172022.csv',
             columns=['Variable', 'Net_Carbon'],
             index=False
             )

## 2 - Add Carbon Harvest
The Merch_Carbon_Stored column tells us how much carbon total has been stored.
Some managements require management at the start, while some require continual managing.

Cost Frequency:
 - ASV: Every Cycle
 - IFM: Once
 - THNB: Once
 - AWR: Once
 - CAR: Once
 - NAR: Once
 - SAR: Once

For a management that gets managed once, we add the final carbon stored to the 2021 figure.
For ASV, we do it like Net Carbon, taking the new harvest carbon each year.

It's not quite right to do ASV the same way, butttttt I will because I don't see how else to extract
carbon numbers. Doing per cycle ignores the impact of carbon decay :/

In [10]:
once_costs = ['IFM', 'THNB', 'AWR', 'CAR', 'NAR', 'SAR']
repeated_costs = ['ASV']

In [25]:
df_hrv = copy.deepcopy(df_seq)
df_hrv.sort_values(['MgmtID', 'StandID', 'Year'])

Net_Carbon        Variable StandID MgmtID  Year  Merch_Carbon_Stored
0     0.122047    505_2021_ASV     505    ASV  2021             0.000083
1     4.206501    505_2025_ASV     505    ASV  2025             0.179192
2     3.996429    505_2030_ASV     505    ASV  2030             0.372516
3    31.035625    505_2050_ASV     505    ASV  2050             1.162175
16  -18.667194    608_2021_AWR     608    AWR  2021            11.303518
17   -5.682604    608_2025_AWR     608    AWR  2025             9.906696
18   -0.463524    608_2030_AWR     608    AWR  2030             8.775704
19   25.571611    608_2050_AWR     608    AWR  2050             6.953076
24   -2.206302    999_2021_AWR     999    AWR  2021             1.319345
25   -0.463110    999_2025_AWR     999    AWR  2025             1.158689
26    2.231233    999_2030_AWR     999    AWR  2030             1.027353
27   23.561516    999_2050_AWR     999    AWR  2050             0.810735
28   -2.206302    999_2021_CAR     999    CAR  2021             1.319345
29   -0.706893    999_2025_CAR     999    CAR  2025             1.158689
30    0.822885    999_2030_CAR     999    CAR  2030             1.027353
31   18.675200    999_2050_CAR     999    CAR  2050             0.810735
4    -2.463722    505_2021_IFM     505    IFM  2021             1.492325
5     1.496395    505_2025_IFM     505    IFM  2025             1.235478
6     3.317268    505_2030_IFM     505    IFM  2030             1.043617
7    20.950588    505_2050_IFM     505    IFM  2050             0.803028
32   -2.203596    999_2021_NAR     999    NAR  2021             1.319345
33   -0.900875    999_2025_NAR     999    NAR  2025             1.158689
34    0.184769    999_2030_NAR     999    NAR  2030             1.027353
35   15.447171    999_2050_NAR     999    NAR  2050             0.810735
8     0.000000   505_2021_PLSQ     505   PLSQ  2021             0.000000
9     4.322262   505_2025_PLSQ     505   PLSQ  2025             0.000000
10    5.055492   505_2030_PLSQ     505   PLSQ  2030             0.000000
11   25.973648   505_2050_PLSQ     505   PLSQ  2050             0.000000
20    0.000000   608_2021_PLSQ     608   PLSQ  2021             0.000000
21    3.243416   608_2025_PLSQ     608   PLSQ  2025             0.000000
22    3.187153   608_2030_PLSQ     608   PLSQ  2030             0.000000
23   15.234692   608_2050_PLSQ     608   PLSQ  2050             0.000000
36    0.000000   999_2021_PLSQ     999   PLSQ  2021             0.000000
37   -0.101026   999_2025_PLSQ     999   PLSQ  2025             0.000000
38    0.098066   999_2030_PLSQ     999   PLSQ  2030             0.000000
39    1.249969   999_2050_PLSQ     999   PLSQ  2050             0.000000
44    0.000000  167N_2021_PLSQ    167N   PLSQ  2021             0.000000
45    1.848362  167N_2025_PLSQ    167N   PLSQ  2025             0.000000
46   -0.386124  167N_2030_PLSQ    167N   PLSQ  2030             0.000000
47    6.949192  167N_2050_PLSQ    167N   PLSQ  2050             0.000000
52    0.000000  167S_2021_PLSQ    167S   PLSQ  2021             0.000000
53    5.697899  167S_2025_PLSQ    167S   PLSQ  2025             0.000000
54    6.045704  167S_2030_PLSQ    167S   PLSQ  2030             0.000000
55   14.331242  167S_2050_PLSQ    167S   PLSQ  2050             0.000000
40   -2.206302    999_2021_SAR     999    SAR  2021             1.319345
41   -0.635398    999_2025_SAR     999    SAR  2025             1.158689
42    1.112241    999_2030_SAR     999    SAR  2030             1.027353
43   20.716050    999_2050_SAR     999    SAR  2050             0.810735
12   -1.386257   505_2021_THNB     505   THNB  2021             0.858615
13    1.413326   505_2025_THNB     505   THNB  2025             0.685010
14    2.903717   505_2030_THNB     505   THNB  2030             0.559091
15   27.720749   505_2050_THNB     505   THNB  2050             0.418785
48   -0.584286  167N_2021_THNB    167N   THNB  2021             0.290956
49    1.044975  167N_2025_THNB    167N   THNB  2025           

In [34]:
# Step 1 - Extract 2050 harvest carbon numbers
df_hrv_2050 = df_hrv[df_hrv['Year'] == 2050]
# If you want to filter out ASV, uncomment the below
# df_hrv_2050 = df_hrv_2050[df_hrv_2050['MgmtID'] != 'ASV']

df_hrv_2050 = df_hrv_2050[['Year', 'StandID', 'MgmtID', 'Merch_Carbon_Stored']]
# As a cheat, we relabel the year to 2021 so it merges with 2021 years
df_hrv_2050 = df_hrv_2050.assign(Year = 2021)
df_hrv_2050 = df_hrv_2050.rename(columns={
    'Merch_Carbon_Stored': 'Carbon_Stored_2050'
})

df_hrv_2050

Year StandID MgmtID  Carbon_Stored_2050
3   2021     505    ASV            1.162175
7   2021     505    IFM            0.803028
11  2021     505   PLSQ            0.000000
15  2021     505   THNB            0.418785
19  2021     608    AWR            6.953076
23  2021     608   PLSQ            0.000000
27  2021     999    AWR            0.810735
31  2021     999    CAR            0.810735
35  2021     999    NAR            0.810735
39  2021     999   PLSQ            0.000000
43  2021     999    SAR            0.810735
47  2021    167N   PLSQ            0.000000
51  2021    167N   THNB            0.126821
55  2021    167S   PLSQ            0.000000
59  2021    167S   THNB            0.171641

In [35]:
# Step 2 - Combine with actual df and add harvest to 2021 numbers
dup_hrv = copy.deepcopy(df_hrv)

dup_hrv = dup_hrv.merge(df_hrv_2050,
            how='left',
            on=['Year', 'StandID', 'MgmtID'],
            validate='many_to_one'
            )

dup_hrv = dup_hrv.fillna(0)
dup_hrv['Net_Carbon'] = dup_hrv['Net_Carbon'] + dup_hrv['Carbon_Stored_2050']

dup_hrv

Net_Carbon        Variable StandID MgmtID  Year  Merch_Carbon_Stored  \
0     1.284222    505_2021_ASV     505    ASV  2021             0.000083   
1     4.206501    505_2025_ASV     505    ASV  2025             0.179192   
2     3.996429    505_2030_ASV     505    ASV  2030             0.372516   
3    31.035625    505_2050_ASV     505    ASV  2050             1.162175   
4    -1.660694    505_2021_IFM     505    IFM  2021             1.492325   
5     1.496395    505_2025_IFM     505    IFM  2025             1.235478   
6     3.317268    505_2030_IFM     505    IFM  2030             1.043617   
7    20.950588    505_2050_IFM     505    IFM  2050             0.803028   
8     0.000000   505_2021_PLSQ     505   PLSQ  2021             0.000000   
9     4.322262   505_2025_PLSQ     505   PLSQ  2025             0.000000   
10    5.055492   505_2030_PLSQ     505   PLSQ  2030             0.000000   
11   25.973648   505_2050_PLSQ     505   PLSQ  2050             0.000000   
12   -0.967472   505_2021_THNB     505   THNB  2021             0.858615   
13    1.413326   505_2025_THNB     505   THNB  2025             0.685010   
14    2.903717   505_2030_THNB     505   THNB  2030             0.559091   
15   27.720749   505_2050_THNB     505   THNB  2050             0.418785   
16  -11.714118    608_2021_AWR     608    AWR  2021            11.303518   
17   -5.682604    608_2025_AWR     608    AWR  2025             9.906696   
18   -0.463524    608_2030_AWR     608    AWR  2030             8.775704   
19   25.571611    608_2050_AWR     608    AWR  2050             6.953076   
20    0.000000   608_2021_PLSQ     608   PLSQ  2021             0.000000   
21    3.243416   608_2025_PLSQ     608   PLSQ  2025             0.000000   
22    3.187153   608_2030_PLSQ     608   PLSQ  2030             0.000000   
23   15.234692   608_2050_PLSQ     608   PLSQ  2050             0.000000   
24   -1.395567    999_2021_AWR     999    AWR  2021             1.319345   
25   -0.463110    999_2025_AWR     999    AWR  2025             1.158689   
26    2.231233    999_2030_AWR     999    AWR  2030             1.027353   
27   23.561516    999_2050_AWR     999    AWR  2050             0.810735   
28   -1.395567    999_2021_CAR     999    CAR  2021             1.319345   
29   -0.706893    999_2025_CAR     999    CAR  2025             1.158689   
30    0.822885    999_2030_CAR     999    CAR  2030             1.027353   
31   18.675200    999_2050_CAR     999    CAR  2050             0.810735   
32   -1.392861    999_2021_NAR     999    NAR  2021             1.319345   
33   -0.900875    999_2025_NAR     999    NAR  2025             1.158689   
34    0.184769    999_2030_NAR     999    NAR  2030             1.027353   
35   15.447171    999_2050_NAR     999    NAR  2050             0.810735   
36    0.000000   999_2021_PLSQ     999   PLSQ  2021             0.000000   
37   -0.101026   999_2025_PLSQ     999   PLSQ  2025             0.000000   
38    0.098066   999_2030_PLSQ     999   PLSQ  2030             0.000000   
39    1.249969   999_2050_PLSQ     999   PLSQ  2050             0.000000   
40   -1.395567    999_2021_SAR     999    SAR  2021             1.319345   
41   -0.635398    999_2025_SAR     999    SAR  2025             1.158689   
42    1.112241    999_2030_SAR     999    SAR  2030             1.027353   
43   20.716050    999_2050_SAR     999    SAR  2050             0.810735   
44    0.000000  167N_2021_PLSQ    167N   PLSQ  2021             0.000000   
45    1.848362  167N_2025_PLSQ    167N   PLSQ  2025             0.000000   
46   -0.386124  167N_2030_PLSQ    167N   PLSQ  2030             0.000000   
47    6.949192  167N_2050_PLSQ    167N   PLSQ  2050             0.000000   
48   -0.457464  167N_2021_THNB    167N   THNB  2021             0.290956   
49    1.044975  167N_2025_THNB    167N   THNB  2025             0.224930   
50    1.089890  167N_2030_THNB    167N   THNB  2030             0.177456   
51   21.187469  167N_2050_THNB    167N   THNB  2050 

In [ ]:
# Step 3 - Do ASV harvest carbon (NOT DONE, COMMENT LEFT FOR REFERENCE)
#
# This should be systemized, but because it's a small # entries,
# I did it manually.
#
#   	Net_Carbon 	Variable     	StandID 	MgmtID 	Year 	Merch_Carbon_Stored 	Carbon_Stored_2050
# 0 	0.122047 	505_2021_ASV 	505     	ASV 	2021 	0.000083 	0.000000
# 1 	4.206501 	505_2025_ASV 	505     	ASV 	2025 	0.179192 	0.000000
# 2 	3.996429 	505_2030_ASV 	505     	ASV 	2030 	0.372516 	0.000000
# 3 	31.035625 	505_2050_ASV 	505     	ASV 	2050 	1.162175 	0.000000
# 
# So, merch_carbon for 2021 = 
#


In [37]:
df_hrv = dup_hrv.drop(columns=[
    'Carbon_Stored_2050', 'Merch_Carbon_Stored'
])

df_hrv

Net_Carbon        Variable StandID MgmtID  Year
0     1.284222    505_2021_ASV     505    ASV  2021
1     4.206501    505_2025_ASV     505    ASV  2025
2     3.996429    505_2030_ASV     505    ASV  2030
3    31.035625    505_2050_ASV     505    ASV  2050
4    -1.660694    505_2021_IFM     505    IFM  2021
5     1.496395    505_2025_IFM     505    IFM  2025
6     3.317268    505_2030_IFM     505    IFM  2030
7    20.950588    505_2050_IFM     505    IFM  2050
8     0.000000   505_2021_PLSQ     505   PLSQ  2021
9     4.322262   505_2025_PLSQ     505   PLSQ  2025
10    5.055492   505_2030_PLSQ     505   PLSQ  2030
11   25.973648   505_2050_PLSQ     505   PLSQ  2050
12   -0.967472   505_2021_THNB     505   THNB  2021
13    1.413326   505_2025_THNB     505   THNB  2025
14    2.903717   505_2030_THNB     505   THNB  2030
15   27.720749   505_2050_THNB     505   THNB  2050
16  -11.714118    608_2021_AWR     608    AWR  2021
17   -5.682604    608_2025_AWR     608    AWR  2025
18   -0.463524    608_2030_AWR     608    AWR  2030
19   25.571611    608_2050_AWR     608    AWR  2050
20    0.000000   608_2021_PLSQ     608   PLSQ  2021
21    3.243416   608_2025_PLSQ     608   PLSQ  2025
22    3.187153   608_2030_PLSQ     608   PLSQ  2030
23   15.234692   608_2050_PLSQ     608   PLSQ  2050
24   -1.395567    999_2021_AWR     999    AWR  2021
25   -0.463110    999_2025_AWR     999    AWR  2025
26    2.231233    999_2030_AWR     999    AWR  2030
27   23.561516    999_2050_AWR     999    AWR  2050
28   -1.395567    999_2021_CAR     999    CAR  2021
29   -0.706893    999_2025_CAR     999    CAR  2025
30    0.822885    999_2030_CAR     999    CAR  2030
31   18.675200    999_2050_CAR     999    CAR  2050
32   -1.392861    999_2021_NAR     999    NAR  2021
33   -0.900875    999_2025_NAR     999    NAR  2025
34    0.184769    999_2030_NAR     999    NAR  2030
35   15.447171    999_2050_NAR     999    NAR  2050
36    0.000000   999_2021_PLSQ     999   PLSQ  2021
37   -0.101026   999_2025_PLSQ     999   PLSQ  2025
38    0.098066   999_2030_PLSQ     999   PLSQ  2030
39    1.249969   999_2050_PLSQ     999   PLSQ  2050
40   -1.395567    999_2021_SAR     999    SAR  2021
41   -0.635398    999_2025_SAR     999    SAR  2025
42    1.112241    999_2030_SAR     999    SAR  2030
43   20.716050    999_2050_SAR     999    SAR  2050
44    0.000000  167N_2021_PLSQ    167N   PLSQ  2021
45    1.848362  167N_2025_PLSQ    167N   PLSQ  2025
46   -0.386124  167N_2030_PLSQ    167N   PLSQ  2030
47    6.949192  167N_2050_PLSQ    167N   PLSQ  2050
48   -0.457464  167N_2021_THNB    167N   THNB  2021
49    1.044975  167N_2025_THNB    167N   THNB  2025
50    1.089890  167N_2030_THNB    167N   THNB  2030
51   21.187469  167N_2050_THNB    167N   THNB  2050
52    0.000000  167S_2021_PLSQ    167S   PLSQ  2021
53    5.697899  167S_2025_PLSQ    167S   PLSQ  2025
54    6.045704  167S_2030_PLSQ    167S   PLSQ  2030
55   14.331242  167S_2050_PLSQ    167S   PLSQ  2050
56   -0.759386  167S_2021_THNB    167S   THNB  2021
57    0.696815  167S_2025_THNB    167S   THNB  2025
58    1.144730  167S_2030_THNB    167S   THNB  2030
59   24.205189  167S_2050_THNB    167S   THNB  2050

In [39]:
df_hrv.to_csv('./run4_correctcarboncosts/Objective_NetSeq_NoHarvest_08172022.csv',
             columns=['Variable', 'Net_Carbon'],
             index=False
             )

## 3 - Add Carbon Costs
Here, we take a user specified cost of each mgmt by forest type. 

We probably also need to scale it up by years since not all periods are equal length but that's future work -\\\_(ツ)_/-

In [9]:
COSTS_DICT = {
    '167N': {
        'PLSQ': 0,
        'THNB': 10
    },
    '167S': {
        'PLSQ': 0,
        'THNB': 10
    },
    '505': {
        'PLSQ': 0,
        'ASV': 0,
        'IFM': 0,
        'THNB': 10
    },
    '608': {
        'PLSQ': 0,
        'AWR': 0
    },
    '999': {
        'PLSQ': 0,
        'AWR': 0,
        'CAR': 0,
        'NAR': 0,
        'SAR': 0
    }
}

In [107]:
def create_dataframe_from_costs (cost_dict: dict) -> dict:
    # The format of the dict isn't actually all that good for converting to a dataframe
    # so we need some ~finangeling~ for it to work    
    pd_dict = {
        'StandID': [],
        'MgmtID': [],
        'Mgmt_Cost': []
    }

    for_types = cost_dict.keys()
    for f in for_types:
        mgmts = cost_dict[f].keys()
        for mg in mgmts:
            cost = cost_dict[f][mg]

            pd_dict['StandID'].append(f)
            pd_dict['MgmtID'].append(mg)
            pd_dict['Mgmt_Cost'].append(cost)
    
    _df = pd.DataFrame.from_dict(pd_dict)
    return _df

create_dataframe_from_costs(COSTS_DICT)

StandID MgmtID  Mgmt_Cost
0     167N   PLSQ          0
1     167N   THNB         10
2     167S   PLSQ          0
3     167S   THNB         10
4      505   PLSQ          0
5      505    ASV          0
6      505    IFM          0
7      505   THNB         10
8      608   PLSQ          0
9      608    AWR          0
10     999   PLSQ          0
11     999    AWR          0
12     999    CAR          0
13     999    NAR          0
14     999    SAR          0

In [109]:
# Now we append the management cost to the main df, and subtract it from net_carbon
def subtract_costs_df (_df_all, _cost_dict: dict):
    '''
    Returns a copy of the df_all, but where the 'Net_Carbon' column
    had the management costs in df_costs removed.
    '''
    _df_costs = create_dataframe_from_costs(_cost_dict)
    
    # The underscores in front of the variables is to avoid any scope
    # ex: df_mgcosts exists outside this function, so using _df_mgcosts removes
    #     the possibility of editing the outside-function df
    _df_mgcost = _df_all.merge(
        _df_costs,
        how='left',
        on=['StandID', 'MgmtID'],
        validate='many_to_one'
    )
    
    _df_mgcost['Net_Carbon'] = _df_mgcost['Net_Carbon'] - _df_mgcost['Mgmt_Cost']
    _df_mgcost = _df_mgcost.drop(columns=['Mgmt_Cost'])
    
    return _df_mgcost

df_mgcost = subtract_costs_df(df_hrv, COSTS_DICT)
df_mgcost

Variable StandID MgmtID  Year  Net_Carbon
0   167N_2021_PLSQ    167N   PLSQ  2021    0.000000
1   167N_2025_PLSQ    167N   PLSQ  2025    1.848362
2   167N_2030_PLSQ    167N   PLSQ  2030   -0.386124
3   167N_2050_PLSQ    167N   PLSQ  2050    6.949192
4   167N_2021_THNB    167N   THNB  2021  -10.584286
5   167N_2025_THNB    167N   THNB  2025   -8.955025
6   167N_2030_THNB    167N   THNB  2030   -8.910110
7   167N_2050_THNB    167N   THNB  2050   11.187469
8   167S_2021_PLSQ    167S   PLSQ  2021    0.000000
9   167S_2025_PLSQ    167S   PLSQ  2025    5.697899
10  167S_2030_PLSQ    167S   PLSQ  2030    6.045704
11  167S_2050_PLSQ    167S   PLSQ  2050   14.331242
12  167S_2021_THNB    167S   THNB  2021  -10.931026
13  167S_2025_THNB    167S   THNB  2025   -9.303185
14  167S_2030_THNB    167S   THNB  2030   -8.855270
15  167S_2050_THNB    167S   THNB  2050   14.205189
16    505_2021_ASV     505    ASV  2021    0.122047
17    505_2025_ASV     505    ASV  2025    4.206501
18    505_2030_ASV     505    ASV  2030    3.996429
19    505_2050_ASV     505    ASV  2050   31.035625
20    505_2021_IFM     505    IFM  2021   -2.463722
21    505_2025_IFM     505    IFM  2025    1.496395
22    505_2030_IFM     505    IFM  2030    3.317268
23    505_2050_IFM     505    IFM  2050   20.950588
24   505_2021_PLSQ     505   PLSQ  2021    0.000000
25   505_2025_PLSQ     505   PLSQ  2025    4.322262
26   505_2030_PLSQ     505   PLSQ  2030    5.055492
27   505_2050_PLSQ     505   PLSQ  2050   25.973648
28   505_2021_THNB     505   THNB  2021  -11.386257
29   505_2025_THNB     505   THNB  2025   -8.586674
30   505_2030_THNB     505   THNB  2030   -7.096283
31   505_2050_THNB     505   THNB  2050   17.720749
32    608_2021_AWR     608    AWR  2021  -18.667194
33    608_2025_AWR     608    AWR  2025   -5.682604
34    608_2030_AWR     608    AWR  2030   -0.463524
35    608_2050_AWR     608    AWR  2050   25.571611
36   608_2021_PLSQ     608   PLSQ  2021    0.000000
37   608_2025_PLSQ     608   PLSQ  2025    3.243416
38   608_2030_PLSQ     608   PLSQ  2030    3.187153
39   608_2050_PLSQ     608   PLSQ  2050   15.234692
40    999_2021_AWR     999    AWR  2021   -2.206302
41    999_2025_AWR     999    AWR  2025   -0.463110
42    999_2030_AWR     999    AWR  2030    2.231233
43    999_2050_AWR     999    AWR  2050   23.561516
44    999_2021_CAR     999    CAR  2021   -2.206302
45    999_2025_CAR     999    CAR  2025   -0.706893
46    999_2030_CAR     999    CAR  2030    0.822885
47    999_2050_CAR     999    CAR  2050   18.675200
48    999_2021_NAR     999    NAR  2021   -2.203596
49    999_2025_NAR     999    NAR  2025   -0.900875
50    999_2030_NAR     999    NAR  2030    0.184769
51    999_2050_NAR     999    NAR  2050   15.447171
52   999_2021_PLSQ     999   PLSQ  2021    0.000000
53   999_2025_PLSQ     999   PLSQ  2025   -0.101026
54   999_2030_PLSQ     999   PLSQ  2030    0.098066
55   999_2050_PLSQ     999   PLSQ  2050    1.249969
56    999_2021_SAR     999    SAR  2021   -2.206302
57    999_2025_SAR     999    SAR  2025   -0.635398
58    999_2030_SAR     999    SAR  2030    1.112241
59    999_2050_SAR     999    SAR  2050   20.716050

## Generating & Exporting Objective Files
In this section, we auto-generate 100s of objective files by varying different costs of managements.

To show another capabability, we afterwards fix the cost of a management and vary the harvest carbon,
again generating 100s of objective files.

Would be interesting also to see the regions (2D, 3D, 4D etc) grid where PLSQ is preffered to management
See: https://plotly.com/python/trisurf/

In [13]:
# df_mgcost.to_csv('./ObjectiveFile_MngCost_0802022.csv',
#               columns=['Variable', 'Net_Carbon'],
#               index=False
#              )

In [26]:
df_mgcost.sort_values(['Year', 'StandID', 'MgmtID'])

Variable StandID MgmtID  Year  Net_Carbon
0   167N_2021_PLSQ    167N   PLSQ  2021    0.000000
4   167N_2021_THNB    167N   THNB  2021  -10.584286
8   167S_2021_PLSQ    167S   PLSQ  2021    0.000000
12  167S_2021_THNB    167S   THNB  2021  -10.931026
16    505_2021_ASV     505    ASV  2021    0.122047
20    505_2021_IFM     505    IFM  2021   -2.463722
24   505_2021_PLSQ     505   PLSQ  2021    0.000000
28   505_2021_THNB     505   THNB  2021  -11.386257
32    608_2021_AWR     608    AWR  2021  -18.667194
36   608_2021_PLSQ     608   PLSQ  2021    0.000000
40    999_2021_AWR     999    AWR  2021   -2.206302
44    999_2021_CAR     999    CAR  2021   -2.206302
48    999_2021_NAR     999    NAR  2021   -2.203596
52   999_2021_PLSQ     999   PLSQ  2021    0.000000
56    999_2021_SAR     999    SAR  2021   -2.206302
1   167N_2025_PLSQ    167N   PLSQ  2025    1.848362
5   167N_2025_THNB    167N   THNB  2025   -8.955025
9   167S_2025_PLSQ    167S   PLSQ  2025    5.697899
13  167S_2025_THNB    167S   THNB  2025   -9.303185
17    505_2025_ASV     505    ASV  2025    4.206501
21    505_2025_IFM     505    IFM  2025    1.496395
25   505_2025_PLSQ     505   PLSQ  2025    4.322262
29   505_2025_THNB     505   THNB  2025   -8.586674
33    608_2025_AWR     608    AWR  2025   -5.682604
37   608_2025_PLSQ     608   PLSQ  2025    3.243416
41    999_2025_AWR     999    AWR  2025   -0.463110
45    999_2025_CAR     999    CAR  2025   -0.706893
49    999_2025_NAR     999    NAR  2025   -0.900875
53   999_2025_PLSQ     999   PLSQ  2025   -0.101026
57    999_2025_SAR     999    SAR  2025   -0.635398
2   167N_2030_PLSQ    167N   PLSQ  2030   -0.386124
6   167N_2030_THNB    167N   THNB  2030   -8.910110
10  167S_2030_PLSQ    167S   PLSQ  2030    6.045704
14  167S_2030_THNB    167S   THNB  2030   -8.855270
18    505_2030_ASV     505    ASV  2030    3.996429
22    505_2030_IFM     505    IFM  2030    3.317268
26   505_2030_PLSQ     505   PLSQ  2030    5.055492
30   505_2030_THNB     505   THNB  2030   -7.096283
34    608_2030_AWR     608    AWR  2030   -0.463524
38   608_2030_PLSQ     608   PLSQ  2030    3.187153
42    999_2030_AWR     999    AWR  2030    2.231233
46    999_2030_CAR     999    CAR  2030    0.822885
50    999_2030_NAR     999    NAR  2030    0.184769
54   999_2030_PLSQ     999   PLSQ  2030    0.098066
58    999_2030_SAR     999    SAR  2030    1.112241
3   167N_2050_PLSQ    167N   PLSQ  2050    6.949192
7   167N_2050_THNB    167N   THNB  2050   11.187469
11  167S_2050_PLSQ    167S   PLSQ  2050   14.331242
15  167S_2050_THNB    167S   THNB  2050   14.205189
19    505_2050_ASV     505    ASV  2050   31.035625
23    505_2050_IFM     505    IFM  2050   20.950588
27   505_2050_PLSQ     505   PLSQ  2050   25.973648
31   505_2050_THNB     505   THNB  2050   17.720749
35    608_2050_AWR     608    AWR  2050   25.571611
39   608_2050_PLSQ     608   PLSQ  2050   15.234692
43    999_2050_AWR     999    AWR  2050   23.561516
47    999_2050_CAR     999    CAR  2050   18.675200
51    999_2050_NAR     999    NAR  2050   15.447171
55   999_2050_PLSQ     999   PLSQ  2050    1.249969
59    999_2050_SAR     999    SAR  2050   20.716050

Here's how I want to try sampling different costs:

- **167N** the cost of THNB to be inside the interval \[-1, 10\]
- **505** is tricky as there are 3 different managements, so we can take a cube where the cost for each type ranges from \[-1, 10\]. Alternatively we can vary each one individually.
- **608** has just one mng, AWR
- **999** again has a couple managements. We have AWR, CAR, NAR, SAR, all of which we can range from \[-1, 10\]

When a management is not the active one being managed, we set the cost of all others to 10 (except PLSQ which is always 0)

For each interval, I want to take at least 100 samples. This means overall we're making 400 objective files (999 has 4 different costs that need varying).

In [144]:
SAMPLES_PER_MNG = 100
COST_LOW = -1
COST_HIGH = 10
# The managements to vary the cost of
MNGS_DICT = {
    '167N': ['THNB'],
    '167S': ['THNB'],
    '505': ['ASV', 'IFM', 'THNB'],
    '608': ['AWR'],
    '999': ['AWR', 'CAR', 'NAR', 'SAR']
}

OBJ_EXPORT_FOLDER = '/home/velcro/Documents/Professional/NJDEP/TechWork/ForMOM/minimodel-running/run3_carboncosts/runs_varying_carboncost/objectives/'
COST_EXPORT_FOLDER = '/home/velcro/Documents/Professional/NJDEP/TechWork/ForMOM/minimodel-running/run3_carboncosts/runs_varying_carboncost/'


In [113]:
# Now comes the fun part of actually doing this
max_number_mngs = max([len(MNGS_DICT[ft]) for ft in FOR_TYPES])
total_num_samples = max_number_mngs * SAMPLES_PER_MNG

In [114]:
samples_per_ft_per_mng = {}

for ft in FOR_TYPES:
    num_mng = len(MNGS_DICT[ft])
    sample_per_mng = total_num_samples // num_mng
    # It's important we get exactly total_num_samples datapoints,
    # so the samples for the last mng might have a little extra
    sample_last_mng = total_num_samples - (num_mng - 1) * sample_per_mng
    
    ft_mngs = MNGS_DICT[ft]
    ft_num_mngs_dict = {}
    
    for ind, mng in enumerate(ft_mngs):
        if ind == num_mng - 1:
            ft_num_mngs_dict[mng] = sample_last_mng
        else:
            ft_num_mngs_dict[mng] = sample_per_mng
    
#     print(f"For ft {ft}, we have the following # samples per mng")
#     print(ft_num_mngs_dict)
#     print()
    samples_per_ft_per_mng[ft] = ft_num_mngs_dict

samples_per_ft_per_mng

{'167S': {'THNB': 400},
 '505': {'ASV': 133, 'IFM': 133, 'THNB': 134},
 '167N': {'THNB': 400},
 '999': {'AWR': 100, 'CAR': 100, 'NAR': 100, 'SAR': 100},
 '608': {'AWR': 400}}

In [125]:
# Generate dictionary of parallel arrays showing the costs in each run

def_cost = COST_HIGH
ind = 0

costs_across_runs = {}
for ft in FOR_TYPES:
    costs_across_runs[ft] = {}
    
    # PLSQ is always 0 cost
    costs_across_runs[ft]['PLSQ'] = list(np.linspace(0, 0, num=total_num_samples, endpoint=True))
    sum_inds = 0
    
    for mng in MNGS_DICT[ft]:
        costs_across_runs[ft][mng] = list(np.linspace(
            COST_HIGH, 
            COST_HIGH, 
            num=total_num_samples, 
            endpoint=True
        ))
        
        n_sample = samples_per_ft_per_mng[ft][mng]
        start_ind = sum_inds
        end_ind = start_ind + n_sample
        
        costs_across_runs[ft][mng][start_ind:end_ind] = list(np.linspace(
            COST_LOW,
            COST_HIGH,
            num=n_sample,
            endpoint=True
        ))
        
        # This needs to be at the end
        sum_inds = end_ind


costs_across_runs

{'167S': {'PLSQ': [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,


In [147]:
# Now, build the objective files!
# This means, for each sample, we build a COST_DICT, make a dataframe from it, and export
all_costs = []

for ind in range(total_num_samples):
    baseline_costs = {}
    
    for ft in FOR_TYPES:
        baseline_costs[ft] = {}
        mngs = costs_across_runs[ft].keys()
        
        for mng in mngs:
            baseline_costs[ft][mng] = costs_across_runs[ft][mng][ind]
    all_costs.append(baseline_costs)
    
    df_objective = subtract_costs_df(df_hrv, baseline_costs)
    
    # Export this objective file
    filename = f'ObjectiveFile_VaryingCost_0802022_{ind}.csv'
    df_objective.to_csv(
        OBJ_EXPORT_FOLDER + filename,
        columns=['Variable', 'Net_Carbon'],
        index=False
    )    

In [146]:
# To make exporting the costs easier, a dataframe is constructed

# This is what the dataframe will look like:
#
# run  StandID  MgmtID  Mgmt_Cost
# 0    167N     PLSQ    0
# 0    167N     THNB    -1
# 0    167S     PLSQ    0
#  .     .       .      .
#  .     .       .      .
#  .     .       .      .
# 235  999      Nar    2.88
# 235  505      IFM    7.5
# 235  505      THNB   10.0
# 235  505      PLSQ   10.0
df_costs_all_runs = None

for ind, costs in enumerate(all_costs):
    df_indcost = create_dataframe_from_costs(costs)
    df_indcost.insert(loc=0, column='Run', value=ind)
    
    if type(df_costs_all_runs) == type(None):
        df_costs_all_runs = df_indcost
    else:
        df_costs_all_runs = pd.concat([df_costs_all_runs, df_indcost])

df_costs_all_runs.to_csv(COST_EXPORT_FOLDER + 'RunCosts.csv')
        
df_costs_all_runs

Run StandID MgmtID  Mgmt_Cost
0     0    167S   PLSQ        0.0
1     0    167S   THNB       -1.0
2     0     505   PLSQ        0.0
3     0     505    ASV       -1.0
4     0     505    IFM       10.0
..  ...     ...    ...        ...
10  399     999    CAR       10.0
11  399     999    NAR       10.0
12  399     999    SAR       10.0
13  399     608   PLSQ        0.0
14  399     608    AWR       10.0

[6000 rows x 4 columns]

## Exporting Objective Files