
--
-- Creates a new table for standids
--

CREATE TABLE NEW_FVS_STANDINIT_PLOT AS
SELECT
    *
FROM
    FVS_STANDINIT_PLOT;

DROP TABLE FVS_STANDINIT_PLOT;

ALTER TABLE
    NEW_FVS_STANDINIT_PLOT RENAME TO FVS_STANDINIT_PLOT;